pragma Singleton

import QtQuick
import Quickshell
import Quickshell.Io
import qs.services
import qs.modules.common
import qs.modules.common.functions

/**
 * System theming: icon/GTK/cursor themes + matugen app templates.
 * Theme lists come from the standard theme dirs; apply goes through
 * scripts/theming/*.sh (ported from the rofi settings-menu).
 * Matugen templates are parsed at runtime from the user's own
 * config.toml.orig (backed up once from config.toml on first run —
 * it stays the source of truth). ~/.config/matugen/config.toml is then
 * regenerated from it, skipping templates listed in
 * Config.options.appearance.matugenDisabled.
 */
Singleton {
    id: root

    readonly property string scriptDir: FileUtils.trimFileProtocol(`${Directories.scriptPath}/theming`)
    readonly property string matugenConfigPath: FileUtils.trimFileProtocol(`${Directories.config}/matugen/config.toml`)

    property list<string> iconThemes: []
    property list<string> gtkThemes: []
    property list<string> cursorThemes: []
    property string currentIconTheme: ""
    property string currentGtkTheme: ""
    property string currentCursorTheme: ""
    property int currentCursorSize: 24

    // Parsed from config.toml.orig: everything before the first [templates.*]
    // header (the [config] section etc.), kept verbatim
    property string matugenPreamble: ""
    // [{name, block}] — block is the raw TOML text of that template, verbatim
    property list<var> matugenTemplates: []

    function templateEnabled(name) {
        return !Config.options.appearance.matugenDisabled.includes(name)
    }

    function setTemplateEnabled(name, on) {
        const disabled = Config.options.appearance.matugenDisabled
        if (on === !disabled.includes(name)) return
        Config.options.appearance.matugenDisabled = on
            ? disabled.filter(n => n !== name)
            : disabled.concat([name])
        root.regenerateMatugenConfig()
    }

    function refresh() {
        scanProc.running = true
    }

    function applyIconTheme(theme) {
        root.currentIconTheme = theme
        Quickshell.execDetached(["bash", `${root.scriptDir}/set-icon-theme.sh`, theme])
    }

    function applyGtkTheme(theme) {
        root.currentGtkTheme = theme
        Quickshell.execDetached(["bash", `${root.scriptDir}/set-gtk-theme.sh`, theme])
    }

    // Writes every cursor sink: gsettings + ~/.icons/default + niri (qssettings/shell.kdl)
    function applyCursorTheme(theme, size) {
        root.currentCursorTheme = theme
        root.currentCursorSize = size
        NiriConfig.options.cursor.theme = theme
        NiriConfig.options.cursor.size = size
        if (theme !== "")
            Quickshell.execDetached(["bash", `${root.scriptDir}/set-cursor-theme.sh`, theme, String(size)])
    }

    function regenerateMatugenConfig() {
        if (root.matugenTemplates.length === 0) return // orig not parsed (yet) — never clobber
        let toml = "# ! AUTO-GENERATED by the shell settings app — do not edit, changes will be overwritten\n"
        toml += "# Edit config.toml.orig instead (source of truth), toggle templates in Settings > Interface.\n\n"
        toml += root.matugenPreamble.trim() + "\n\n"
        for (const tpl of root.matugenTemplates) {
            if (!root.templateEnabled(tpl.name)) continue
            toml += tpl.block.trim() + "\n\n"
        }
        matugenConfigFile.setText(toml)
    }

    readonly property list<var> matugenSchemeOptions: [
        { displayName: Translation.tr("Automatic"), value: "auto" },
        { displayName: Translation.tr("Tonal spot"), value: "scheme-tonal-spot" },
        { displayName: Translation.tr("Expressive"), value: "scheme-expressive" },
        { displayName: Translation.tr("Fidelity"), value: "scheme-fidelity" },
        { displayName: Translation.tr("Fruit salad"), value: "scheme-fruit-salad" },
        { displayName: Translation.tr("Monochrome"), value: "scheme-monochrome" },
        { displayName: Translation.tr("Neutral"), value: "scheme-neutral" },
        { displayName: Translation.tr("Rainbow"), value: "scheme-rainbow" },
        { displayName: Translation.tr("Content"), value: "scheme-content" }
    ]

    function validSchemeType(type) {
        return matugenSchemeOptions.some(option => option.value === type)
    }

    function normalizeSchemeName(name) {
        return (name || "").trim().replace(/\s+/g, " ")
    }

    function normalizeAccentColor(color) {
        const value = (color || "").trim()
        return value === "" || /^#?[0-9a-fA-F]{6}$/.test(value)
            ? (value === "" ? "" : (value.startsWith("#") ? value : `#${value}`))
            : ""
    }

    function saveCustomScheme(name, type, accentColor) {
        const normalizedName = normalizeSchemeName(name)
        const normalizedType = validSchemeType(type) ? type : "auto"
        if (normalizedName === "") return false

        const scheme = { name: normalizedName, type: normalizedType, accentColor: normalizeAccentColor(accentColor) }
        const schemes = Config.options.appearance.palette.customSchemes.filter(item => item && item.name !== normalizedName)
        Config.options.appearance.palette.customSchemes = schemes.concat([scheme])
        return true
    }

    function removeCustomScheme(name) {
        Config.options.appearance.palette.customSchemes = Config.options.appearance.palette.customSchemes.filter(item => item && item.name !== name)
    }

    function applyCustomScheme(scheme) {
        if (!scheme || !validSchemeType(scheme.type)) return
        Config.options.appearance.palette.type = scheme.type
        Config.options.appearance.palette.accentColor = normalizeAccentColor(scheme.accentColor)
        root.regenerateColors()
    }

    // Re-run matugen + color generation with the current wallpaper
    function regenerateColors() {
        Quickshell.execDetached(["bash", Directories.wallpaperSwitchScriptPath, "--noswitch"])
    }

    FileView {
        id: matugenConfigFile
        path: root.matugenConfigPath
    }

    // Backs up config.toml -> config.toml.orig once, then emits the orig
    // for parsing. The .orig stays the user's hand-written source of truth.
    Process {
        id: matugenSourceProc
        running: true
        command: ["bash", "-c", `
            cfg='${root.matugenConfigPath}'
            [ -f "$cfg" ] && [ ! -f "$cfg.orig" ] && cp "$cfg" "$cfg.orig"
            cat "$cfg.orig" 2>/dev/null || true
        `]
        stdout: StdioCollector {
            onStreamFinished: {
                const templates = []
                let preambleLines = []
                let current = null
                for (const line of text.split("\n")) {
                    const header = line.match(/^\s*\[templates\.([^\]]+)\]/)
                    if (header) {
                        current = { name: header[1].replace(/["']/g, ""), lines: [line] }
                        templates.push(current)
                    } else if (/^\s*\[/.test(line)) { // some other [section]
                        current = null
                        preambleLines.push(line)
                    } else if (current) {
                        current.lines.push(line)
                    } else {
                        preambleLines.push(line)
                    }
                }
                root.matugenPreamble = preambleLines.join("\n")
                root.matugenTemplates = templates.map(t => ({ name: t.name, block: t.lines.join("\n") }))
            }
        }
    }

    Process {
        id: scanProc
        running: true
        command: ["bash", "-c", `
            echo :::ICON
            find /usr/share/icons "$HOME/.local/share/icons" "$HOME/.icons" -mindepth 1 -maxdepth 1 -type d 2>/dev/null | xargs -r -n1 basename | sort -u | grep -Evx 'hicolor|default'
            echo :::GTK
            find /usr/share/themes "$HOME/.themes" "$HOME/.local/share/themes" -mindepth 1 -maxdepth 1 -type d 2>/dev/null | xargs -r -n1 basename | sort -u
            echo :::CURSOR
            find /usr/share/icons "$HOME/.local/share/icons" "$HOME/.icons" -mindepth 2 -maxdepth 2 -type d -name cursors 2>/dev/null | sed 's|/cursors$||' | xargs -r -n1 basename | sort -u
            echo :::CURRENT
            (gsettings get org.gnome.desktop.interface icon-theme 2>/dev/null || echo) | tr -d "'"
            (gsettings get org.gnome.desktop.interface gtk-theme 2>/dev/null || echo) | tr -d "'"
            (gsettings get org.gnome.desktop.interface cursor-theme 2>/dev/null || echo) | tr -d "'"
            gsettings get org.gnome.desktop.interface cursor-size 2>/dev/null || echo 24
        `]
        stdout: StdioCollector {
            onStreamFinished: {
                const data = { ICON: [], GTK: [], CURSOR: [], CURRENT: [] }
                let bucket = ""
                for (const rawLine of text.split("\n")) {
                    const line = rawLine.trim()
                    if (line.startsWith(":::")) {
                        bucket = line.slice(3)
                        continue
                    }
                    if (bucket && bucket in data) data[bucket].push(line)
                }
                root.iconThemes = data.ICON.filter(l => l !== "")
                root.gtkThemes = data.GTK.filter(l => l !== "")
                root.cursorThemes = data.CURSOR.filter(l => l !== "")
                root.currentIconTheme = data.CURRENT[0] ?? ""
                root.currentGtkTheme = data.CURRENT[1] ?? ""
                root.currentCursorTheme = data.CURRENT[2] ?? ""
                root.currentCursorSize = parseInt(data.CURRENT[3]) || 24
            }
        }
    }
}
